# -----------------------------------
# SERVER CONFIG
# -----------------------------------
server.port=${PORT:8093}
spring.application.name=notification-service
health.services.userService=http://localhost:8091/api/v1/users/instructor
health.services.courseService=http://localhost:8083/api/v1/courses
health.timeout=2000

# -----------------------------------
# DATABASE (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_NAME:lms_notification_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:cyberlearnix}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cyberlearnix123}
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------------
# JPA / HIBERNATE
# -----------------------------------
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.default-property-inclusion=non_empty

# -----------------------------------
# LOGGING
# -----------------------------------
logging.level.org.springframework=INFO
logging.level.com.example.notification=DEBUG

# -----------------------------------
# KAFKA (optional for later)
# -----------------------------------
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

# -----------------------------------
# REDIS (optional for caching)
# -----------------------------------
spring.redis.host=localhost
spring.redis.port=6379

# -----------------------------------
# EMAIL (SMTP)
# -----------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cyberlearnix@gmail.com
spring.mail.password=qxzn mhwz tigg iywl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# -----------------------------------
# JWT (for security later)
# -----------------------------------
jwt.expiration=3600000
jwt.access-token.secret=8c4e9d2f1a7b6c5d9e3f0a1b7c8d4e5f9a2b6c1d8e7f3a4b5c9d1e6f8a2b7c3

# -----------------------------------
# FIREBASE (Push Notifications)
# -----------------------------------
firebase.service-account.path=firebase-service-account.json