server:
  port: 8082

spring:
  application:
    name: coupon-service

  # 1. Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_coupon_db
    username: shivasai
    password: '1932'
    driver-class-name: org.postgresql.Driver

  # 2. Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379

  # 3. Security Configuration (FIXED SYNTAX)
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-data: |
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsivgmsskqdvzKh4ReHAh2BWC0mcFGgmH5byQh2bNbPqo31GJN9gNkkTwavUuxbKJyb5auGy9OFZYFnP4zAzfMpEjWqvLu+hjqgC33PAOrcD3w4mK/VkqkQcLcw2R3E71L2H+1PrQdEuJ1P01jz5j9iO0QRab30M2DHu91plkYdFAClWF0QUymJaq6JDt4qtKmYX9M1jm8eqL9Idy+36GGOW15ECzbw0ERpNalQtEQL5ovi/xfqEpYUP4d3FlbnkscuDDhXOl382qAdB8SRKO7LtbktEIOLD7a0lfOIOa3u4Vwr/XCHw8x4FEmVFQ4kL6vGDHtabKgbdUusfkLC4LYwIDAQAB

  # 4. JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # 5. Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  cache:
    type: none