package com.example.admin.security;

import com.cyberlearnix.security.SharedJwtValidator;
import com.example.admin.entity.Admin;
import com.example.admin.entity.AssignedService;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.security.Keys;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;
import java.util.UUID;

@Service
@Slf4j
public class JwtService {

    private static final String DEFAULT_SECRET =
            "8c4e9d2f1a7b6c5d9e3f0a1b7c8d4e5f9a2b6c1d8e7f3a4b5c9d1e6f8a2b7c3";

    private static final String ISSUER = "cyberlearnix";

    private final SecretKey key;
    private final SharedJwtValidator sharedJwtValidator;

    public JwtService(
            @Value("${jwt.secret:" + DEFAULT_SECRET + "}") String secret,
            SharedJwtValidator sharedJwtValidator) {
        this.key = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
        this.sharedJwtValidator = sharedJwtValidator;
    }

    private static final long ACCESS_TOKEN_EXPIRATION = 60 * 60 * 1000; // 1 hour
    private static final long REFRESH_TOKEN_EXPIRATION = 7L * 24 * 60 * 60 * 1000; // 7 days

    // ================= TOKEN GENERATION (Service-to-service only) =================
    // Admin login tokens are now generated by User Service
    
    public String generateServiceToken(String role) {
        return generateServiceToken(role, UUID.fromString("11111111-1111-1111-1111-111111111111"));
    }

    public String generateServiceToken(String role, UUID subject) {
        return generateServiceToken(role, subject, null);
    }

    public String generateServiceToken(String role, UUID subject, AssignedService assignedService) {
        String roleWithPrefix = role.startsWith("ROLE_") ? role : "ROLE_" + role;
        var builder = Jwts.builder()
                .setSubject(subject.toString())
                .setIssuer(ISSUER)
                .setAudience("cyberlearnix-clients")
                .claim("role", roleWithPrefix)
                .claim("type", "access");

        if (assignedService != null) {
            builder.claim("assignedService", assignedService.name());
        }

        return builder
                .setIssuedAt(new Date())
                .setExpiration(new Date(System.currentTimeMillis() + ACCESS_TOKEN_EXPIRATION))
                .signWith(key, SignatureAlgorithm.HS256)
                .compact();
    }

    public HttpHeaders createServiceAuthHeaders() {
        return createServiceAuthHeaders("MAIN_ADMIN");
    }

    public HttpHeaders createServiceAuthHeaders(String role) {
        HttpHeaders headers = new HttpHeaders();
        headers.set("Authorization", "Bearer " + generateServiceToken(role));
        return headers;
    }

    // ================= CLAIM EXTRACTION (using shared validator) =================
    public UUID extractAdminId(String token) {
        try {
            String userId = sharedJwtValidator.extractUserId(token);
            return UUID.fromString(userId);
        } catch (Exception e) {
            log.error("Failed to extract admin ID from token", e);
            throw new JwtException("Invalid token");
        }
    }

    public String extractRole(String token) {
        try {
            return sharedJwtValidator.extractRole(token);
        } catch (Exception e) {
            log.error("Failed to extract role from token", e);
            throw new JwtException("Invalid token");
        }
    }

    public String extractEmail(String token) {
        try {
            return sharedJwtValidator.extractEmail(token);
        } catch (Exception e) {
            log.error("Failed to extract email from token", e);
            return null;
        }
    }

    public String extractAdminType(String token) {
        try {
            String value = sharedJwtValidator.extractAdminType(token);
            return "NONE".equals(value) ? null : value;
        } catch (Exception e) {
            log.error("Failed to extract admin type from token", e);
            return null;
        }
    }

    public AssignedService extractAssignedService(String token) {
        try {
            String value = sharedJwtValidator.extractAssignedService(token);
            if (value == null || value.isBlank() || "NONE".equals(value)) {
                return null;
            }
            return AssignedService.valueOf(value);
        } catch (Exception e) {
            log.error("Failed to extract assigned service from token", e);
            return null;
        }
    }

    // ================= TOKEN VALIDATION (using shared validator) =================
    public boolean validateToken(String token) {
        return sharedJwtValidator.isTokenValid(token);
    }
}