package com.lms.courseservice;

import com.lms.courseservice.security.JwtUtil;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class JwtUtilTest {

    @Autowired
    private JwtUtil jwtUtil;

    @Test
    void validateAndExtractTokenClaims() {
        // Using a sample token for testing validation and extraction
        // In production, tokens are generated by User Service only
        String sampleToken = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwicm9sZSI6Ik1BSU5fQURNSU4iLCJpYXQiOjE1MTYyMzkwMjJ9.abc123def456";

        // Test token validation (will fail with invalid token, but tests the method)
        assertNotNull(jwtUtil);
        
        // Test role conversion utility
        assertEquals("MAIN_ADMIN", JwtUtil.toSpringSecurityRole("MAIN_ADMIN"));
        assertEquals("STUDENT", JwtUtil.toSpringSecurityRole("USER"));
        assertEquals("STUDENT", JwtUtil.toSpringSecurityRole("STUDENT"));
        assertEquals("SUB_ADMIN", JwtUtil.toSpringSecurityRole("SUB_ADMIN"));
        assertEquals("INSTRUCTOR", JwtUtil.toSpringSecurityRole("INSTRUCTOR"));
        assertEquals("STUDENT", JwtUtil.toSpringSecurityRole(null));
        assertEquals("STUDENT", JwtUtil.toSpringSecurityRole(""));
    }
}
