server:
  port: 8081

spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://localhost:5432/lms_cart_db
    username: shivasai
    password: "1932"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Removed explicit dialect to stop the HHH90000025 warning
    open-in-view: false # Recommended for performance

  # Stops the "Generated Security Password" warning in console
  security:
    user:
      name: user
      password: password

  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.security: INFO   # Reduced noise but kept security logs
    org.hibernate.SQL: DEBUG